import { redirect } from 'next/navigation';
import { DashboardShell } from '@/components/dashboard/DashboardShell';
import { PendingLink } from '@/components/system/PendingLink';
import { FormSubmitButton } from '@/components/system/FormSubmitButton';
import { getDashboardTenant } from '@/lib/auth';
import { buildExecutiveAnalytics } from '@/services/analytics';
import { withTimeout } from '@/lib/performance';

export const dynamic = 'force-dynamic';

type AnalyticsPageProps = {
  searchParams: Promise<{ demo?: string }>;
};

function numberFormat(value: number) {
  return new Intl.NumberFormat('en-US').format(value);
}

function MetricCard({ label, value, help }: { label: string; value: string; help: string }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-3 text-3xl font-black text-slate-950">{value}</p>
      <p className="mt-2 text-sm leading-6 text-slate-500">{help}</p>
    </div>
  );
}

function ProgressRow({ label, value }: { label: string; value: number }) {
  return (
    <div className="grid gap-2">
      <div className="flex items-center justify-between text-sm">
        <span className="font-bold text-slate-700">{label}</span>
        <span className="font-black text-slate-950">{value}%</span>
      </div>
      <div className="h-2 rounded-full bg-slate-100">
        <div className="h-2 rounded-full bg-[#2155d9]" style={{ width: `${Math.min(100, value)}%` }} />
      </div>
    </div>
  );
}

function CountList({ items, empty }: { items: Array<{ name: string; count: number }>; empty: string }) {
  if (items.length === 0) return <p className="rounded-xl border border-dashed border-slate-200 p-4 text-sm font-semibold text-slate-500">{empty}</p>;
  return (
    <div className="grid gap-3">
      {items.map((item) => (
        <div key={item.name} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3">
          <span className="text-sm font-bold text-slate-700">{item.name}</span>
          <span className="rounded-full bg-white px-2.5 py-1 text-xs font-black text-slate-950 shadow-sm">{numberFormat(item.count)}</span>
        </div>
      ))}
    </div>
  );
}

export default async function AnalyticsPage({ searchParams }: AnalyticsPageProps) {
  const tenant = await getDashboardTenant(4000);
  if (tenant.status === 'unauthenticated') redirect('/sign-in');
  if (tenant.status === 'organization_missing' || tenant.status === 'onboarding_incomplete') redirect('/onboarding');
  if (!tenant.organization) redirect('/dashboard');

  const query = await searchParams;
  const demoProjection = query.demo === '1';
  const report = await withTimeout(
    'executive analytics page',
    buildExecutiveAnalytics(tenant.organization.id, { demoProjection }),
    2800,
  );
  const exportSuffix = demoProjection ? '&demo=1' : '';

  return (
    <DashboardShell>
      <section className="grid gap-6">
        <div className="overflow-hidden rounded-3xl border border-slate-200 bg-[#07111f] p-6 text-white shadow-sm sm:p-7">
          <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-200">Executive ROI Dashboard</p>
              <h2 className="mt-2 text-3xl font-black tracking-tight text-white">Business value generated by ApprovLine</h2>
              <p className="mt-3 max-w-4xl text-base leading-7 text-slate-200">{report.summary}</p>
              {report.demoProjection ? (
                <span className="mt-4 inline-flex rounded-full border border-blue-300/30 bg-blue-400/10 px-3 py-1 text-xs font-black uppercase tracking-wide text-blue-100">
                  Demo projection enabled
                </span>
              ) : null}
            </div>
            <div className="flex flex-wrap gap-2">
              <PendingLink href={`/api/export/analytics?format=csv${exportSuffix}`} pendingText="Preparing CSV..." className="inline-flex min-h-0 h-11 items-center justify-center rounded-xl border border-white/15 bg-white/10 px-4 text-sm font-bold text-white hover:bg-white/15">
                CSV Export
              </PendingLink>
              <PendingLink href={`/api/export/analytics?format=pdf${exportSuffix}`} pendingText="Preparing PDF..." className="inline-flex min-h-0 h-11 items-center justify-center rounded-xl bg-[#2155d9] px-4 text-sm font-bold text-white shadow-sm shadow-blue-950/30 hover:bg-[#2f66ff]">
                PDF Executive Report
              </PendingLink>
            </div>
          </div>
        </div>

        <div className="flex flex-col justify-between gap-3 rounded-2xl border border-blue-100 bg-blue-50/70 p-4 shadow-sm sm:flex-row sm:items-center">
          <div>
            <h3 className="font-black text-slate-950">Demo mode for executive meetings</h3>
            <p className="mt-1 text-sm font-semibold text-slate-600">Use realistic monthly projections from demo data when presenting ROI before live customer data accumulates.</p>
          </div>
          <div className="flex flex-wrap gap-2">
            <PendingLink href="/analytics?demo=1" pendingText="Loading demo..." className="inline-flex min-h-0 h-10 items-center justify-center rounded-lg bg-[#2155d9] px-4 text-sm font-bold text-white shadow-sm shadow-blue-200">
              Use demo analytics
            </PendingLink>
            <form action="/api/demo/seed" method="post">
              <FormSubmitButton pendingText="Generating..." className="inline-flex min-h-0 h-10 items-center justify-center rounded-lg border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 shadow-sm">
                Generate demo data
              </FormSubmitButton>
            </form>
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
          <MetricCard label="Approvals captured" value={numberFormat(report.approvals.total)} help="Total approval and rejection decisions in the executive reporting window." />
          <MetricCard label="Time saved" value={`${numberFormat(report.timeSaved.totalHours)} hrs`} help="Estimated manual search, retrieval, and audit preparation effort avoided." />
          <MetricCard label="High-risk approvals" value={numberFormat(report.riskReduction.highRiskApprovalsDetected)} help="Security, compliance, legal, finance, and procurement decisions surfaced for review." />
          <MetricCard label="Traceability" value={`${report.complianceReadiness.approvalTraceability}%`} help="Records with approver, source, timestamp, and decision context." />
        </div>

        <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Approvals captured</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Department coverage</h3>
            <div className="mt-5">
              <CountList items={report.approvals.byDepartment} empty="Approval departments appear after records are captured." />
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Source coverage</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Approvals by source</h3>
            <div className="mt-5">
              <CountList items={report.approvals.bySource} empty="Source data appears after Slack or Gmail ingestion runs." />
            </div>
          </div>
        </div>

        <div className="grid gap-6 xl:grid-cols-3">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Time saved</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Operational effort avoided</h3>
            <div className="mt-5 grid gap-3">
              <MetricCard label="Manual search" value={`${numberFormat(report.timeSaved.manualSearchHours)} hrs`} help="Time avoided searching Slack, Gmail, and audit trails." />
              <MetricCard label="Audit prep" value={`${numberFormat(report.timeSaved.auditPreparationHours)} hrs`} help="Evidence reconstruction effort avoided." />
              <MetricCard label="Retrieval" value={`${numberFormat(report.timeSaved.retrievalHours)} hrs`} help="Approval lookup and source-link retrieval time avoided." />
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Risk reduction</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Controls surfaced</h3>
            <div className="mt-5 grid gap-3">
              {[
                ['Missing approvals detected', report.riskReduction.missingApprovalsDetected],
                ['Conditional approvals detected', report.riskReduction.conditionalApprovalsDetected],
                ['High-risk approvals detected', report.riskReduction.highRiskApprovalsDetected],
                ['Approvals without evidence', report.riskReduction.approvalsWithoutEvidence],
              ].map(([label, value]) => (
                <div key={label as string} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3">
                  <span className="text-sm font-bold text-slate-700">{label}</span>
                  <span className="text-lg font-black text-slate-950">{numberFormat(value as number)}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Compliance readiness</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Audit posture</h3>
            <div className="mt-5 grid gap-5">
              <ProgressRow label="Audit completeness" value={report.complianceReadiness.auditCompleteness} />
              <ProgressRow label="Evidence coverage" value={report.complianceReadiness.evidenceCoverage} />
              <ProgressRow label="Approval traceability" value={report.complianceReadiness.approvalTraceability} />
            </div>
          </div>
        </div>

        <div className="grid gap-6 xl:grid-cols-[0.85fr_1.15fr]">
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Integration insights</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Connector contribution</h3>
            <div className="mt-5 grid gap-3">
              {[
                ['Slack approvals', report.integrations.slackApprovals],
                ['Gmail approvals', report.integrations.gmailApprovals],
                ['Teams approvals', report.integrations.teamsApprovals],
                ['Outlook approvals', report.integrations.outlookApprovals],
              ].map(([label, value]) => (
                <div key={label as string} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3">
                  <span className="font-bold text-slate-700">{label}</span>
                  <span className="font-black text-slate-950">{numberFormat(value as number)}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs font-black uppercase tracking-wide text-[#2155d9]">Playbook AI insights</p>
            <h3 className="mt-1 text-lg font-black text-slate-950">Policy intelligence</h3>
            <div className="mt-5 grid gap-5 lg:grid-cols-2">
              <div>
                <p className="text-sm font-black text-slate-950">{numberFormat(report.playbookAi.questionsAsked)} questions asked</p>
                <div className="mt-3">
                  <CountList items={report.playbookAi.mostReferencedPolicies} empty="Referenced policies appear after Playbook AI answers questions." />
                </div>
              </div>
              <div className="grid gap-4">
                <div>
                  <p className="text-xs font-black uppercase tracking-wide text-slate-500">Missing policy areas</p>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {(report.playbookAi.missingPolicyAreas.length ? report.playbookAi.missingPolicyAreas : ['No missing policy areas detected']).map((item) => (
                      <span key={item} className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-800">{item}</span>
                    ))}
                  </div>
                </div>
                <div>
                  <p className="text-xs font-black uppercase tracking-wide text-slate-500">Approval bottlenecks</p>
                  <div className="mt-2">
                    <CountList items={report.playbookAi.approvalBottlenecks} empty="Bottlenecks appear when conditional or pending records exist." />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </DashboardShell>
  );
}
