export type JobOperationalOwner = 'platform' | 'integrations' | 'ai' | 'founder-ops';

export interface JobRegistryEntry {
  jobType: string;
  queueName: string;
  trigger: string;
  tenantContext: 'required';
  retryPolicy: string;
  maxAttempts: number;
  timeoutMs: number;
  idempotencyStrategy: string;
  failureHandling: string;
  deadLetterBehavior: string;
  operationalOwner: JobOperationalOwner;
  priority: number;
}

export const jobRegistry: JobRegistryEntry[] = [
  {
    jobType: 'approval.classify',
    queueName: 'approval-classification',
    trigger: 'API ingestion, webhooks, email/transcript/document extraction, connector syncs',
    tenantContext: 'required',
    retryPolicy: '5 attempts, exponential backoff with jitter for transient failures',
    maxAttempts: 5,
    timeoutMs: 15_000,
    idempotencyStrategy: 'tenant-scoped idempotency key + source hash + external ID dedupe',
    failureHandling: 'Record failed job and provider state, retry transient failures only',
    deadLetterBehavior: 'Move unrecoverable payloads to approval dead-letter storage',
    operationalOwner: 'integrations',
    priority: 90,
  },
  {
    jobType: 'gateway.outbox.flush',
    queueName: 'approval-classification',
    trigger: 'Readiness checks, queue recovery, opportunistic route flush',
    tenantContext: 'required',
    retryPolicy: '3 attempts, short exponential backoff',
    maxAttempts: 3,
    timeoutMs: 8_000,
    idempotencyStrategy: 'outbox ID + tenant-scoped idempotency key',
    failureHandling: 'Keep outbox pending until retry window expires',
    deadLetterBehavior: 'Escalate to founder operations after repeated failure',
    operationalOwner: 'platform',
    priority: 70,
  },
  {
    jobType: 'csv.import.process',
    queueName: 'content-processing',
    trigger: 'CSV uploads and historical approval imports',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for parsing and storage interruptions',
    maxAttempts: 4,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped import batch ID + content hash',
    failureHandling: 'Mark import chunk failed, continue safe records, retry transient storage failures',
    deadLetterBehavior: 'Persist failed chunk payloads for founder replay',
    operationalOwner: 'platform',
    priority: 60,
  },
  {
    jobType: 'document.ingest.process',
    queueName: 'content-processing',
    trigger: 'Policy, contract, invoice, and document uploads',
    tenantContext: 'required',
    retryPolicy: '4 attempts, bounded retry for parser or OCR interruptions',
    maxAttempts: 4,
    timeoutMs: 30_000,
    idempotencyStrategy: 'tenant-scoped document hash + upload ID',
    failureHandling: 'Record parser failure, keep source artifact, retry transient extraction failures',
    deadLetterBehavior: 'Move redacted document job metadata to content dead-letter storage',
    operationalOwner: 'ai',
    priority: 55,
  },
  {
    jobType: 'transcript.ingest.process',
    queueName: 'content-processing',
    trigger: 'Zoom, Teams, and uploaded transcript ingestion',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for transcript extraction and storage failures',
    maxAttempts: 4,
    timeoutMs: 25_000,
    idempotencyStrategy: 'tenant-scoped transcript hash + external transcript ID',
    failureHandling: 'Store transcript failure context and retry transient provider issues',
    deadLetterBehavior: 'Preserve transcript metadata in dead-letter queue for replay',
    operationalOwner: 'integrations',
    priority: 65,
  },
  {
    jobType: 'integration.sync.slack',
    queueName: 'integration-sync',
    trigger: 'Manual syncs, scheduled sync windows, connector recovery',
    tenantContext: 'required',
    retryPolicy: '5 attempts, provider-aware exponential backoff honoring retry-after',
    maxAttempts: 5,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped sync cursor + provider event IDs',
    failureHandling: 'Mark integration unhealthy only on permanent auth/provider errors',
    deadLetterBehavior: 'Create integration dead-letter record and founder alert',
    operationalOwner: 'integrations',
    priority: 80,
  },
  {
    jobType: 'integration.sync.gmail',
    queueName: 'integration-sync',
    trigger: 'Scheduled Gmail mailbox syncs and manual refresh',
    tenantContext: 'required',
    retryPolicy: '5 attempts, retry-after aware exponential backoff',
    maxAttempts: 5,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped Gmail message ID + sync cursor',
    failureHandling: 'Preserve last successful cursor and retry transient provider failures',
    deadLetterBehavior: 'Move failed Gmail sync batch to dead-letter storage',
    operationalOwner: 'integrations',
    priority: 80,
  },
  {
    jobType: 'integration.sync.teams',
    queueName: 'integration-sync',
    trigger: 'Scheduled Teams syncs and manual sync requests',
    tenantContext: 'required',
    retryPolicy: '5 attempts, exponential backoff for Graph API interruptions',
    maxAttempts: 5,
    timeoutMs: 22_000,
    idempotencyStrategy: 'tenant-scoped Teams message ID + delta token',
    failureHandling: 'Pause only affected connector state on permanent auth failures',
    deadLetterBehavior: 'Store failed Teams sync payload with correlation metadata',
    operationalOwner: 'integrations',
    priority: 80,
  },
  {
    jobType: 'integration.sync.outlook',
    queueName: 'integration-sync',
    trigger: 'Outlook and Exchange sync requests',
    tenantContext: 'required',
    retryPolicy: '5 attempts, retry-after aware backoff for Microsoft Graph failures',
    maxAttempts: 5,
    timeoutMs: 22_000,
    idempotencyStrategy: 'tenant-scoped Outlook message ID + conversation cursor',
    failureHandling: 'Track provider throttling separately from permanent auth failures',
    deadLetterBehavior: 'Move unrecoverable Outlook sync payloads to dead-letter queue',
    operationalOwner: 'integrations',
    priority: 80,
  },
  {
    jobType: 'integration.sync.jira',
    queueName: 'integration-sync',
    trigger: 'Manual Jira syncs and scheduled issue polling',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for Atlassian API interruptions',
    maxAttempts: 4,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped Jira issue/comment ID + sync watermark',
    failureHandling: 'Capture sync watermark and retry only incomplete batches',
    deadLetterBehavior: 'Persist failed Jira sync payloads for replay and founder review',
    operationalOwner: 'integrations',
    priority: 75,
  },
  {
    jobType: 'integration.sync.zoom',
    queueName: 'integration-sync',
    trigger: 'Zoom transcript syncs and meeting evidence refresh',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for transcript and recording fetch failures',
    maxAttempts: 4,
    timeoutMs: 25_000,
    idempotencyStrategy: 'tenant-scoped meeting/transcript ID + recording cursor',
    failureHandling: 'Retry transcript fetches only for transient provider failures',
    deadLetterBehavior: 'Create dead-letter record with redacted meeting metadata',
    operationalOwner: 'integrations',
    priority: 70,
  },
  {
    jobType: 'integration.sync.servicenow',
    queueName: 'integration-sync',
    trigger: 'Scheduled request/change syncs and manual recovery runs',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for REST API failures',
    maxAttempts: 4,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped ServiceNow record ID + update timestamp',
    failureHandling: 'Continue from saved cursor after transient failures',
    deadLetterBehavior: 'Store failed ServiceNow records for replay',
    operationalOwner: 'integrations',
    priority: 70,
  },
  {
    jobType: 'playbook.extract',
    queueName: 'ai-processing',
    trigger: 'Policy uploads and re-index requests',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for AI and parser interruptions',
    maxAttempts: 4,
    timeoutMs: 30_000,
    idempotencyStrategy: 'tenant-scoped document hash + version ID',
    failureHandling: 'Preserve uploaded source, retry transient extraction failures only',
    deadLetterBehavior: 'Route failed playbook jobs to AI dead-letter storage',
    operationalOwner: 'ai',
    priority: 65,
  },
  {
    jobType: 'playbook.embed',
    queueName: 'ai-processing',
    trigger: 'Playbook chunk embedding and indexing',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff with provider timeout handling',
    maxAttempts: 4,
    timeoutMs: 25_000,
    idempotencyStrategy: 'tenant-scoped playbook chunk ID + embedding version',
    failureHandling: 'Retry transient model failures and keep prior index active',
    deadLetterBehavior: 'Move failed embedding batches to AI dead-letter storage',
    operationalOwner: 'ai',
    priority: 60,
  },
  {
    jobType: 'compliance.evaluate',
    queueName: 'ai-processing',
    trigger: 'Approval persistence, playbook updates, manual re-evaluation',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for model and storage failures',
    maxAttempts: 4,
    timeoutMs: 18_000,
    idempotencyStrategy: 'tenant-scoped approval ID + policy version',
    failureHandling: 'Store prior compliance result until recomputation succeeds',
    deadLetterBehavior: 'Escalate failed compliance evaluations to founder observability',
    operationalOwner: 'ai',
    priority: 75,
  },
  {
    jobType: 'investigation.summary.generate',
    queueName: 'ai-processing',
    trigger: 'Investigation creation and investigator refresh requests',
    tenantContext: 'required',
    retryPolicy: '3 attempts, exponential backoff for model or retrieval failures',
    maxAttempts: 3,
    timeoutMs: 18_000,
    idempotencyStrategy: 'tenant-scoped investigation ID + summary version',
    failureHandling: 'Keep manual investigation access available when AI summary fails',
    deadLetterBehavior: 'Record failed summary job without blocking the investigation view',
    operationalOwner: 'ai',
    priority: 55,
  },
  {
    jobType: 'memory.entity.upsert',
    queueName: 'memory-graph',
    trigger: 'Approval writes, contract ingestion, policy ingestion, investigation updates',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for graph persistence failures',
    maxAttempts: 4,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped entity key + source record fingerprint',
    failureHandling: 'Retry transient graph storage failures and audit uncertain duplicates',
    deadLetterBehavior: 'Move unrecoverable entity writes to graph dead-letter storage',
    operationalOwner: 'platform',
    priority: 72,
  },
  {
    jobType: 'memory.relationship.upsert',
    queueName: 'memory-graph',
    trigger: 'Entity creation, policy references, investigation links, gateway events',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for relationship persistence failures',
    maxAttempts: 4,
    timeoutMs: 18_000,
    idempotencyStrategy: 'tenant-scoped edge fingerprint + relationship type',
    failureHandling: 'Retry graph edge failures and preserve timeline evidence separately',
    deadLetterBehavior: 'Escalate persistent edge failures to founder operations',
    operationalOwner: 'platform',
    priority: 68,
  },
  {
    jobType: 'analytics.executive.rebuild',
    queueName: 'analytics',
    trigger: 'Executive ROI refreshes, pilot health recalculations, scheduled rollups',
    tenantContext: 'required',
    retryPolicy: '3 attempts, exponential backoff for aggregate query failures',
    maxAttempts: 3,
    timeoutMs: 15_000,
    idempotencyStrategy: 'tenant-scoped reporting window + metric snapshot key',
    failureHandling: 'Serve last good snapshot until recomputation succeeds',
    deadLetterBehavior: 'Record failed analytics recomputation without blocking customer UI',
    operationalOwner: 'founder-ops',
    priority: 45,
  },
  {
    jobType: 'copilot.index.refresh',
    queueName: 'ai-processing',
    trigger: 'Memory graph updates, playbook changes, approval ingestion',
    tenantContext: 'required',
    retryPolicy: '4 attempts, exponential backoff for indexing interruptions',
    maxAttempts: 4,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped knowledge snapshot ID',
    failureHandling: 'Keep prior Copilot index active until refresh succeeds',
    deadLetterBehavior: 'Move failed Copilot refresh jobs to AI dead-letter storage',
    operationalOwner: 'ai',
    priority: 50,
  },
  {
    jobType: 'export.generate',
    queueName: 'exports',
    trigger: 'CSV, JSON, PDF, and executive report export requests',
    tenantContext: 'required',
    retryPolicy: '3 attempts, bounded retry for rendering and storage failures',
    maxAttempts: 3,
    timeoutMs: 30_000,
    idempotencyStrategy: 'tenant-scoped export request ID + format + filter hash',
    failureHandling: 'Retry transient generation failures, never duplicate export artifacts',
    deadLetterBehavior: 'Store failed export metadata and allow manual founder replay',
    operationalOwner: 'platform',
    priority: 40,
  },
  {
    jobType: 'demo.workspace.generate',
    queueName: 'analytics',
    trigger: 'Founder demo workspace generator',
    tenantContext: 'required',
    retryPolicy: '2 attempts, bounded retry for seed and graph population failures',
    maxAttempts: 2,
    timeoutMs: 45_000,
    idempotencyStrategy: 'tenant-scoped dataset fingerprint + generation request ID',
    failureHandling: 'Reset incomplete demo generation before retrying',
    deadLetterBehavior: 'Escalate failed demo generation to founder operations',
    operationalOwner: 'founder-ops',
    priority: 35,
  },
  {
    jobType: 'customer.health.recalculate',
    queueName: 'analytics',
    trigger: 'Pilot readiness, usage rollups, and founder revenue dashboard refreshes',
    tenantContext: 'required',
    retryPolicy: '3 attempts, exponential backoff for aggregate query failures',
    maxAttempts: 3,
    timeoutMs: 12_000,
    idempotencyStrategy: 'tenant-scoped reporting period + metric version',
    failureHandling: 'Keep last healthy score while retries continue',
    deadLetterBehavior: 'Log failed health-score recalculation for founder review',
    operationalOwner: 'founder-ops',
    priority: 42,
  },
  {
    jobType: 'notification.dispatch',
    queueName: 'notifications',
    trigger: 'Founder alerts, onboarding reminders, pilot tasks, system notifications',
    tenantContext: 'required',
    retryPolicy: '4 attempts, provider-aware exponential backoff',
    maxAttempts: 4,
    timeoutMs: 10_000,
    idempotencyStrategy: 'tenant-scoped notification key + channel',
    failureHandling: 'Retry only transient delivery failures and preserve alert intent',
    deadLetterBehavior: 'Persist failed notification metadata for support review',
    operationalOwner: 'platform',
    priority: 38,
  },
  {
    jobType: 'retention.cleanup',
    queueName: 'retention',
    trigger: 'Scheduled retention and deletion windows',
    tenantContext: 'required',
    retryPolicy: '2 attempts, bounded retry for storage contention',
    maxAttempts: 2,
    timeoutMs: 20_000,
    idempotencyStrategy: 'tenant-scoped retention window + object class',
    failureHandling: 'Abort partial deletion batches and retry from last checkpoint',
    deadLetterBehavior: 'Log failed retention batches for founder remediation',
    operationalOwner: 'platform',
    priority: 20,
  },
];

export interface StandardJobEnvelope<TPayload = Record<string, unknown>> {
  jobType: string;
  organizationId: string;
  workspaceId: string;
  correlationId: string;
  idempotencyKey: string;
  sourceSystem?: string;
  sourceRecordId?: string;
  attemptNumber: number;
  createdAt: string;
  traceId: string;
  priority: number;
  metadata?: Record<string, unknown>;
  payload: TPayload;
}

export function getJobRegistryEntry(jobType: string) {
  return jobRegistry.find((entry) => entry.jobType === jobType) ?? null;
}
